twig:
  form_themes:
    - "@FOSCKEditor/Form/ckeditor_widget.html.twig"

fos_ck_editor:
  configs:
    main_config:
      entities: false
      toolbar:
        - {
            name: "styles",
            items:
              [
                "Bold",
                "Italic",
                "Underline",
                "Strike",
                "Blockquote",
                "-",
                "Link",
                "-",
                "NumberedList",
                "BulletedList",
                "-",
                "Outdent",
                "Indent",
                "-",
                "-",
                "JustifyLeft",
                "JustifyCenter",
                "JustifyRight",
                "JustifyBlock",
                "-",
                "Format",
                "-",
                "TextColor",
                "BGColor",
              ],
          }
